# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicTacToe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Socket.IO-Client-Swift', '~> 8.2.0'
 pod 'RxSwift',    '~> 3.0'
 pod 'RxCocoa',    '~> 3.0'
 # Pods for TicTacToe

  target 'TicTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TicTacToeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
